Feature/datasets filtering
dafnifacility/cli pull request #28
Opened 2021-03-15 15:49 UTC by jamie-short

Added in filters for `dafni get datasets`:
- `--search`: Uses the elastic search on the discovery api to apply a search term(s) to the datasets
- `--start-date`: Applies filtering on the date ranges relating to the datasets
- `--end-date`: Applies filtering on the date ranges relating to the datasets

2021-03-16 16:01 UTC, iroper-tessella requested changes
Couple of typos, and then I wonder if the new util function could be used in the Model class.

2021-03-16 18:26 UTC, jamie-short commented on docs/dafni_cli.md
> +  - **--search-terms**: Option to apply an elastic text search to the available datasets.
I've removed reference to elastic, as it may cause confusion

2021-03-16 18:27 UTC, jamie-short commented on test/test_utils.py
> +    """Test class to test te process_date_filter functionality"""
updated

2021-03-16 18:27 UTC, jamie-short commented on dafni_cli/utils.py
> +        str: Processed date str tp YYYY-MM-DDT00:00:00
updated

2021-03-16 18:27 UTC, jamie-short commented on dafni_cli/utils.py
> +def process_date_filter(date_str: str) -> str:
I'll take a look

2021-03-16 18:29 UTC, jamie-short commented on dafni_cli/utils.py
> +def process_date_filter(date_str: str) -> str:
I dont think it can, as the function returns an iso formatted string, where as filter_by_date requires a datetime.date instance

2021-03-17 09:21 UTC, iroper-tessella approved these changes

2021-03-17 09:21 UTC, merged