Feature/datasets version history
dafnifacility/cli pull request #44
Opened 2021-03-24 20:35 UTC by jamie-short

Added the --version-history/-v flag to the get dataset command, to display the version history instead of the metadata for the given dataset.

To Do:
- Update tests for get.py

2021-03-25 10:41 UTC, iroper-tessella requested changes
Could you add some documentation for the `--version-history` option for get dataset please?

2021-03-25 10:41 UTC, iroper-tessella commented on test/fixtures/dataset_fixtures.py
> +        version_id (str, optional): Dataset Version ID. Defaults to "Annual".
These defaults aren't correct.

2021-03-26 09:02 UTC, jamie-short commented on dafni_cli/datasets/dataset_metadata.py
> +        self.version_id = version_id
good point, hadn't noticed the extra key in the response, updated

2021-03-26 09:02 UTC, jamie-short commented on test/fixtures/dataset_fixtures.py
> +        version_id (str, optional): Dataset Version ID. Defaults to "Annual".
updated

2021-03-26 09:50 UTC, iroper-tessella requested changes
One tiny change needed. Then happy to be merged.

2021-03-26 09:50 UTC, iroper-tessella commented on test/fixtures/dataset_fixtures.py
> +        title (str, optional): Associated Title. Defaults to "en".
This one has default "Title".

2021-03-26 10:06 UTC, iroper-tessella approved these changes

2021-03-26 10:06 UTC, merged